### ISSUE TITLE
zhusuan refactoring broke this repo

### ISSUE THREAD

**Issue by srossi93** [pomonam/NoisyNaturalGradient#3]
Apparently the refactoring of zhusuan broke the code in this repository (at least for regression). For instance `zhusuan.model.StochasticTensor` imported [here](https://github.com/pomonam/NoisyNaturalGradient/blob/cd84820eb3abc3f6dad4fde691679b0af0aecdf3/regression/controller/distributions.py#L7) no longer exists and it seems to be replaced by ` zhusuan.framework.bn.StochasticTensor`. But unfortunately this is not enough to fix the problem. 

I know that asking to fix this issue is too much and zhusuan does not have any tags, but could you please share the last commit hash of zhusuan you know for sure this repo's still working with?

**Comment by pomonam** [comment]
Hi Rossi,

Thank you for letting me know. You can use Zhusuan with this version (tree: 54f536be2d...):
https://github.com/thu-ml/zhusuan/tree/54f536be2d87cf49b6808d05824032e0e07936e8

Juhan
